### ISSUE TITLE
https://www.bluestarmarketing.de/en/marketingcampaigns

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#101]
Das **kleine Bild** austauschen, muss Laptop (mit Steinturm) sein!
Das gilt auch für die DE-Version!

Zweimal das **Apostroph** anpassen, beim ersten Aufzählungspunkt und in der letzten Zeile.

Stages of the buyer’s journey
Let’s find your hidden treasures!

**Comment by danielmoessner** [comment]
bild ist ausgetauscht. apostroph ist dort genauso wie überall anders auch.
