### ISSUE TITLE
Allgemeine Todo Liste

### ISSUE THREAD

**Issue by danielmoessner** [danielmoessner/bluestarmarketing.de#135]
- [x] Bilder austauschen
- [x] Blog Archiv
- [x] Startimes Listenseite
- [x] Startimes Detailseite

**Comment by danielmoessner** [comment]
Offene Fragen: 

- Den Start Artikel ganz oben im Blog verstecken wenn Archiv ausgewählt ist?
- Im CMS die Bilder rausnehmen in der englischen Version der Artikel, dann würden einfach die deutschen übernommen werden?

**Comment by ST-BSM** [comment]
@danielmoessner
Prio 1 
ich füge die 3 Dateien als Preview hier gleich mal mit den allerletzten Korrekturen für dich an, dann bekommst du direkt einen Eindruck. Macht das Anfügen hier sind oder lieber per E-Mail?

[star_times_meet_magic_mates_2023_01_21_b_K-ST.pdf](https://github.com/danielmoessner/bluestarmarketing.de/files/10474039/star_times_meet_magic_mates_2023_01_21_b_K-ST.pdf)
bekommst du schon einen ersten Eindruck :-)
[star_times_2023_01_21_b_K-ST2201.pdf](https://github.com/danielmoessner/bluestarmarketing.de/files/10474037/star_times_2023_01_21_b_K-ST2201.pdf)
[star_times_meet_magic_mates_date#1_2023_01_21_b_K-ST2201.pdf](https://github.com/danielmoessner/bluestarmarketing.de/files/10474038/star_times_meet_magic_mates_date.1_2023_01_21_b_K-ST2201.pdf)

**Comment by ST-BSM** [comment]
**Prio 1**: Star Times > Meet Magic Mates > **Eventseite: 28.2.23**
Prio 2: Star Times > Meet Magic Mates > **Eventseite: 27.4.23**
Prio 2: Star Times > Meet Magic Mates > **Eventseite: 28.6.23**
