### ISSUE TITLE
E-Mail aus dem CMS nach der Anmeldung

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#145]
E-Mail aus dem CMS nach der Anmeldung

wir brauchen hier eine klare Codierung, d.h. ich muss klar zuordnen können idealerweise im Betreff wofür, für welches Format die Anmeldung ist und für welchen Termin

Meet Magic Mates
28.2.2022

Diese Info muss bitte mitgeliefert werden.

-----Ursprüngliche Nachricht-----
Betreff: [Netlify] Form submission from standardformular:

Name:

Unternehmen:
Blue Star Marketing GmbH & Co. KG

E-Mail:
...

Telefon:
...

Nachricht:

**Comment by danielmoessner** [comment]
Hast du das Formular auf der Preview getestet oder auf der Live Seite? Preview Seite scheint bei mir gerade keine Formular-Sendungen bei Netlify einzutragen.
