### ISSUE TITLE
Prio 1: HOME bauen gem PDF

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#27]
Zwischenteil fehlt komplett, ist noch temp V.

**Comment by danielmoessner** [comment]
ist hier noch ein punkt offen?
startseite liegt aktuell hier: http://.../startseite
wird bei launch bewegt auf http://bluestarmarketing.de

**Comment by ST-BSM** [comment]
Korrekt, wie hast du das mit der Navi und der Verknüpfung der Sites geplant?

 

Von: Daniel Mössner ***@***.***> 
Gesendet: Sonntag, 17. Juli 2022 20:31
An: danielmoessner/bluestarmarketing.de ***@***.***>
Cc: ST-BSM ***@***.***>; Author ***@***.***>
Betreff: Re: [danielmoessner/bluestarmarketing.de] Prio 1: HOME bauen gem PDF (Issue #27)

 

ist hier noch ein punkt offen?
startseite liegt aktuell hier: http://.../startseite
wird bei launch bewegt auf http://bluestarmarketing.de
