### ISSUE TITLE
https://www.bluestarmarketing.de/services# - Text in der Kachel Funnel

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#34]
An welchem Punkt benötigt eure Marketing-Pipeline einen echten Push?

An dieser Stelle benötigen wir einen Vertrauensvorschuss, denn Einblicke und Transparenz sind extrem relevant, um Schätze zu finden und Potenziale zu heben. Wir begrüßen und schätzen deine Offenheit, denn es stellen sich viele Fragen, beispielsweise ob bereits ausreichend Leads zur Zielerreichung generiert werden

Am Ende des Textes fehlt ein Punkt

**Comment by danielmoessner** [comment]
angepasst

**Comment by danielmoessner** [comment]
also punkt eingefügt
