### ISSUE TITLE
https://www.bluestarmarketing.de/startseite# CTA bei dem Block Marketingreise zu Wachstum und Erfolg

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#36]
CTA bei dem Block Marketingreise zu Wachstum und Erfolg
geht auf die Services Seite

ist noch nicht verlinkt, bzw. bleibt auf Home

**Comment by danielmoessner** [comment]
gehen jetzt jeweils auf die services
