### ISSUE TITLE
https://www.bluestarmarketing.de/startseite# CTA 1+2 von Abschnitt 1 und 2 auf der Seite

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#37]
beide linksbündigen CTAs haben eine identische Breite
hier sehe ich den Unterschied auf den ersten Blick

CTA 1: Starte deine Marketingreise
CTA 2: Starte deine Wunschrakete

**Comment by danielmoessner** [comment]
Bis auf 2px jetzt gleich breit
