### ISSUE TITLE
ALLE CTA Höhen sind zu hoch - auf allen Seiten - bitte Abgleich mit PDF

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#38]
die CTA wirken so deutlich wuchtiger, da auch deutlich höher, neben der bereits diskutierten varierenden Breiten je nach Textlänge, wenn die CTA direkt übereinander stehen und ich sehe das ohne zu scrollen, dann brauchen sie die gleiche Breite

**Comment by danielmoessner** [comment]
bitte die höhe checken. ist ja wie im call jetzt nicht mehr so hoch
