### ISSUE TITLE
https://www.bluestarmarketing.de/workshop - Fehler 404 - Site verfügbar?

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#40]

**Comment by danielmoessner** [comment]
strategieworkshop ist erreichbar.
fehlermeldung bei seite nicht gefunden ist angepasst.

**Comment by ST-BSM** [comment]
Du hast eine andere URL gewählt, nicht die aus dem File

 

Von: Daniel Mössner ***@***.***> 
Gesendet: Sonntag, 17. Juli 2022 19:38
An: danielmoessner/bluestarmarketing.de ***@***.***>
Cc: ST-BSM ***@***.***>; Author ***@***.***>
Betreff: Re: [danielmoessner/bluestarmarketing.de] https://www.bluestarmarketing.de/workshop - Fehler 404 - Site verfügbar? (Issue #40)

 

strategieworkshop ist erreichbar.
fehlermeldung bei seite nicht gefunden ist angepasst.

**Comment by danielmoessner** [comment]
ah sehr gut anpassung lädt hoch
