### ISSUE TITLE
https://www.bluestarmarketing.de/kontakt - Sternschnuppe fehlt unter der Überschrift Kontakt

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#42]

**Comment by ST-BSM** [comment]
kommt erst beim Scrollen, sehr zeitversetzt, ist es wie bei den anderen Sites oder verzögert?

**Comment by danielmoessner** [comment]
ist überall gleich auf allen seiten. sobald es im screen ist also reingescrollt wartet es kurz und fliegt dann rein. also die sternschnuppe. wenn das für dich so passt gerne schließen.

**Comment by ST-BSM** [comment]
done, hat etwas mit scrollen zu tun
