### ISSUE TITLE
https://www.bluestarmarketing.de/marketingfunnel - bitte Absatz 2 und 3 zentriert / ausgewogen

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#43]
Funnel Grafik
und S-liegend 
sitzen nicht gut, bitte ausrichten, ist schief aus > siehe bitte PDF für Zentrierung

**Comment by danielmoessner** [comment]
leicht nach links verschoben auf gro-en bildschirmen
