### ISSUE TITLE
https://www.bluestarmarketing.de/fuer-dich -> Header Image bitte tauschen

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#44]
Annika sendet dir eine neue Grafik, die Positionierung soll oben rechts sein, meine Hände mit den Sternen zu sehen

**Comment by ST-BSM** [comment]
Die gewünschte Grafik liegt im Folder. Hat Annika schon derzeit so angeliefert.
Bitte ändern

**Comment by danielmoessner** [comment]
text ist nach oben gewandert

**Comment by ST-BSM** [comment]
wo, denn? zeigt nicht die Änderung auch nicht im private Window
