### ISSUE TITLE
https://www.bluestarmarketing.de/fuer-dich - Zitat

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#45]
Farbe Zitat ?? bitte schauen, ist im PDF deutlich dunkler

Text Zitat kursiv und fett?
so ist es sehr schlecht lesbar

Quellenangaben = 2 Zeilen OHNE Zeilenabstand dazwischen

**Comment by danielmoessner** [comment]
angepasst
