### ISSUE TITLE
https://www.bluestarmarketing.de/kontakt > WhatsApp Icon mit Linkedin verknüpft - bitte ändern

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#49]

**Comment by danielmoessner** [comment]
Was soll ich bei dem Whats App Icon einfügen?
Soll es direkt zu Whats app gehen?

**Comment by ST-BSM** [comment]
Linkedin geht hier hin - Company Profile: [www.linkedin.com/company/blue-star-marketing](http://www.linkedin.com/company/blue-star-marketing)

WhatsApp geht auch auf Linkedin?

**Comment by ST-BSM** [comment]
Geht es zu meiner Handynummer bzw. was ist möglich, um mich auf dem Weg zu kontaktieren?

 

Von: Daniel Mössner ***@***.***> 
Gesendet: Sonntag, 17. Juli 2022 19:33
An: danielmoessner/bluestarmarketing.de ***@***.***>
Cc: ST-BSM ***@***.***>; Author ***@***.***>
Betreff: Re: [danielmoessner/bluestarmarketing.de] https://www.bluestarmarketing.de/kontakt > WhatsApp Icon mit Linkedin verknüpft - bitte ändern (Issue #49)

 

Was soll ich bei dem Whats App Icon einfügen?
Soll es direkt zu Whats app gehen?
