### ISSUE TITLE
https://www.bluestarmarketing.de/kontakt -> Linkedin Ikon mit mir verknüpft für den Moment okay oder 2x Linkedin

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#50]
es gibt jetzt ein Firmenprofil
[www.linkedin.com/company/blue-star-marketing](http://www.linkedin.com/company/blue-star-marketing)

**Comment by danielmoessner** [comment]
ist angepasst 2x linkedin macht für mich keinen sinn
