### ISSUE TITLE
Prio 3: https://www.bluestarmarketing.de/kontakt > Nutzung Daten > 2. Auswahlpunkt

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#51]
geht die ausgefüllte Kontaktanfrage per E-Mail an kontakt@bluestarmarketing.de?

können wir hier noch einen 2. Auswahlpunkt einbauen?
Gerne abonniere ich die Star News und möchte diese an meine E-Mail Adresse gesendet bekommen.

Dann müssten wir aber noch die Sache mit der Bestätigungsemail - Link klicken einbauen für Double-Opt-In

**Comment by danielmoessner** [comment]
Genau habe ich eingestellt auf kontakt@

double opt in ist schwierig. brauchen wir ein tool für. müssen wir morgen besprechen.

**Comment by ST-BSM** [comment]
OK 😊

 

Von: Daniel Mössner ***@***.***> 
Gesendet: Sonntag, 17. Juli 2022 20:35
An: danielmoessner/bluestarmarketing.de ***@***.***>
Cc: ST-BSM ***@***.***>; Author ***@***.***>
Betreff: Re: [danielmoessner/bluestarmarketing.de] Prio 3: https://www.bluestarmarketing.de/kontakt > Nutzung Daten > 2. Auswahlpunkt (Issue #51)

 

Genau habe ich eingestellt auf kontakt@

double opt in ist schwierig. brauchen wir ein tool für. müssen wir morgen besprechen.
