### ISSUE TITLE
Star News bitte bauen - Annika hat die PDFs, wie es aussehen soll, die Bilder und die Texte

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#52]
Zum Start nur Post 1 auch als Star News
2-3 Tage später Post 2
2-3 Tage später Post 3

Timings, wenn wir uns besprochen haben und wir Termine fixieren können.

**Comment by danielmoessner** [comment]
post 1 ist drin funktionalität steht. mobil hat extra issue
