### ISSUE TITLE
https://www.bluestarmarketing.de/kunden - BITTE Bildertausch - auch wenn es im PDF anders ist

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#55]
Als Headerbild bitte das 2. /kleine nehmen

und das Headerbild an die 2. Stelle setzen

Danke, ich weiß es war so im PDF, ich denke aber das kleinere Bild hat die bessere Wirkung

**Comment by danielmoessner** [comment]
getauscht
