### ISSUE TITLE
Seite: Services

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#56]
- Im 2. CTA-Button: Potenziale entdecken – Kontakt aufnehmen (Halbgeviertstrich)
- Headline "Das sagen unsere Kund:innen" nicht in Versalien
- Das Zitat in der Box kursiv setzen.
- Bei ERFOLGE FEIERN fehlt noch die Quellenangabe

**Comment by danielmoessner** [comment]
was ist mit versalien gemeint? rest ist erledigt

**Comment by annikalind** [comment]
Versalien = Großbuchstaben
Sorry, Typography-Nerd... ;-)

**Comment by danielmoessner** [comment]
Also Großbuchstaben ist es immer noch aber fett ist es nicht mehr :) wenn es nicht passt gerne kommentar und wieder öffnen
