### ISSUE TITLE
Seite: Unsere Kunden

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#57]
- In den Zitat-Boxen die Zitate kursiv setzen
- In den Zitat-Boxen vielleicht den Zeilenabstand ein kleines bisschen größer?
- Bei "genau richtig" (Text als Bild eingefügt) ist die Grafik unten leicht angeschnitten
- Abstand vor Headline "Das sagen unsere Kund:innen" etwas kleiner, dafür danach (zwischen Headline und Zitat-Boxen) etwas größer
- Bilder austauschen (siehe Issue von Silke, Bilder kamen per Mail)

**Comment by danielmoessner** [comment]
bild müsstest du mal schauen hier: https://www.bluestarmarketing.de/media/genau_richtig_250px.png

rest ist angepasst.
