### ISSUE TITLE
Seite: Kontakt

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#58]
- EIN GEWINN FÜR DICH nicht fett
- bei "genau richtig" (Grafik als Bild eingefügt) ist das wieder unten angeschnitten, es fehlt was vom "g" und es sitzt zu dicht am Text (mehr Abstand zwischen "uns" und "genau")
- Schau noch mal nach der Formatierung im Ansichts-PDF, bzw. die 2 Zeilen so formatieren wie bei der Kunden-Seite
- bei der Aufzählung mit den Sternchen etwas mehr Zeilenabstand

Dass die Textboxen beim Mouse-over oceanfarbig werden, gefällt mir sehr!

**Comment by danielmoessner** [comment]
Das Bild ist glaube ich in der Quelle bereitsch abgeschnitten. Könntest du hier mal schauen: https://www.bluestarmarketing.de/media/genau_richtig_250px.png

Schrift Gewicht ist für mich teilweise schwer zu erkennen. Hast du eine Struktur für h1, h2, h3 usw? bzw feste größen für die unterschiedlichen headlines. können wir dann gerne durchgehen.

issue mal geschlossen, bzgl dem bild kannst du gerne ein neues aufmachen für die anpassunge von dem auf jeder seite. selbes für die überschriften. ansonsten gerne dieses hier wieder aufmachen falls formatierung noch etwas nciht stimmt.
