### ISSUE TITLE
Seite: Für dich

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#59]
- Im ersten Textblock 2 Wort-Trennungen rausnehmen

**Comment by danielmoessner** [comment]
Bitte info welche genau

**Comment by annikalind** [comment]
IT-Monitoring
B2B-Marketingexpertise 

Die beiden Wörter sollten nach Möglichkeit nicht getrennt werden. Also... kein Zeilenumbruch mitten im Wort.

**Comment by danielmoessner** [comment]
Hab da keine gute Möglichkeit. Bindestrich wird standardmäßig als mögliche Stelle für zeilenumbruch verwendet. bin für tipps offen
