### ISSUE TITLE
Services >> Farben

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#62]
Bei SERVICES stimmen in den Boxen die Farbbalken noch nicht. Ist jetzt überall dieselbe, sollte aber unterschiedlich. Entsprechend auch die Farbbalken am Headerbild auf den Unterseiten.

**Comment by danielmoessner** [comment]
teilweise kann ich die farben nicht zu 100% erkennen. ist teilweise ein gradient drin? wobei ohne gradient einfacher wäre, auf jeden fall kann die farbe jz im admin bereich eingestellt werden.

**Comment by annikalind** [comment]
Die Farben sind alle im Brandboard mit HEX-Code. Es ist nur einmal ein Verlauf, bei Sales- & Marketingfunnel.
