### ISSUE TITLE
Seite: Home

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#63]
Vorletzte Headline: @ Silke: Heißt es Dach-Region oder DACH-Region?
Und die Formatierung der Headlines ist in der Ansichts-PDF anders... Das bezieht sich aber auf alle Seiten.

**Comment by danielmoessner** [comment]
ausgebessert zu DACH-Region ist im kleinen text davor nämlich bereits alles groß geschrieben.

Ja überschriften, sollten wir nochmal vereinheitlichen. Könntest du mir dafür alle Styles von denen durchschicken? also quasi 
h1: bold (600) letter spacing: xy uppercase ja nein stern ja nein

irgendwie in die richtung. muss an sich auch gar nciht h1, h2 usw sein styleX, styleY usw geht genauso gut. Ob du es dann für Sektionen vereinheitlichen willst passend zu h1, h2 usw überlasse ich dir.

Überschriften dann bitte in diesem Issue: [https://github.com/danielmoessner/bluestarmarketing.de/issues/61](https://github.com/danielmoessner/bluestarmarketing.de/issues/61)
