### ISSUE TITLE
https://www.bluestarmarketing.de/en/contact

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#87]
2. Block, Untertitel >> Apostroph anpassen

Then you’ve come to the

Beim Kontaktformular unten bei der Checkbox und dem Text noch einen Hinweis auf die Datenschutzerklärung?
(Gilt auch für D)

**Comment by danielmoessner** [comment]
erledigt. Hinweis auf datenschutz ist noch offen in anderem issue
