### ISSUE TITLE
DE/EN

### ISSUE THREAD

**Issue by annikalind** [danielmoessner/bluestarmarketing.de#90]
Wenn man zwischen den Sprachen wechselt, landet man immer auf HOME und bleibt nicht auf der Seite, wo man gerade ist.
Da kenne ich mich nicht so aus, soll das so sein?

**Comment by danielmoessner** [comment]
Ging technisch leider nicht anders. weil die urls unterschiedlich sind beim blog und impressum / datenschutz.
blog/toller-article
en/blog/awesome-article

und da kann ich nicht einfach en davor klatschen.

**Comment by annikalind** [comment]
Ah, ok. Danke für die Info :)
