### ISSUE TITLE
Star News EN #1 - bitte diesen Text einfügen - danke

### ISSUE THREAD

**Issue by ST-BSM** [danielmoessner/bluestarmarketing.de#97]
We joyfully and gratefully are looking back on two successful years that we are happy to celebrate with you, our customers and friends!

For the onward marketing journey, we have designed new modules for your success, based on your very positive feedback. We are happy to present these to you on our brand new website!

With our strategic insights and expertise, we want to enable you to shine, to achieve your goals and to enjoy more free space and time. 

What do you want, and what do you wish for? Please take a moment and celebrate with us, celebrate yourself as well as summer and life in general – and then launch your personal “wish rocket” and visit us at www.bluestarmarketing.de!

**Comment by danielmoessner** [comment]
fehlt noch englischer text bei star news aber soweit angepasst
